[config]
reload_apps = true

[config.reload_apps_list]
kitty = true
gtk_theme = true

[config.wallpaper]
command = "waypaper"
arguments = ["--wallpaper $wallpaper"]
set = false

[templates.avatar]
input_path = './templates/avatar.svg'
output_path = '~/.config/hypr/avatar.svg'

[templates.cava]
input_path = './templates/colors-cava'
output_path = '~/.config/cava/config'

[templates.firefox]
input_path = './templates/pywalfox-colors.json'
output_path = '~/.cache/wal/colors.json'

[templates.fuzzel]
input_path = './templates/colors-fuzzel.ini'
output_path = '~/.config/fuzzel/fuzzel.ini'

[templates.gtk-archdroid-icons]
input_path = './templates/gtk-icons.sh'
output_path = '~/.config/hypr/scripts/archdroid-icon-theme/color.sh'

[templates.hyprland]
input_path = './templates/colors-hyprland.conf'
output_path = '~/.config/hypr/colors.conf'

[templates.kitty]
input_path = '~/.config/matugen/templates/colors-kitty.conf'
output_path = '~/.config/kitty/colors.conf'

[templates.kvantum]
input_path = '~/.config/matugen/templates/colors-kvantum.kvconfig'
output_path = '~/.config/kvantum/matugen/matugen.kvconfig'

[templates.mako]
input_path = './templates/colors-mako.ini'
output_path = '~/.config/mako/config'

[templates.material-gtk-3-assets]
input_path = './templates/gtk-material-color/svg/gtk-3-assets.svg'
output_path = '~/.config/hypr/scripts/materia-theme/src/gtk-3.0/assets.svg'

[templates.material-gtk-theme-color]
input_path = './templates/gtk-material-color/_theme-color.scss'
output_path = '~/.config/hypr/scripts/materia-theme/src/_theme-color.scss'

[templates.mpv]
input_path = './templates/colors-mpv.conf'
output_path = '~/.config/mpv/script-opts/uosc.conf'

[templates.neovim]
input_path = '~/.config/matugen/templates/colors-nvim.vim'
output_path = '~/.cache/wal/colors-wal.vim'

[templates.qt5]
input_path = './templates/colors-qt.conf'
output_path = '~/.config/qt5ct/colors/matugen-colors.conf'

[templates.qt6]
input_path = './templates/colors-qt.conf'
output_path = '~/.config/qt6ct/colors/matugen-colors.conf'

[templates.satty]
input_path = './templates/colors-satty.toml'
output_path = '~/.config/satty/config.toml'

[templates.slurp]
input_path = './templates/colors-slurp.sh'
output_path = '~/.config/kitty/slurp.sh'

[templates.starship]
input_path = './templates/colors-starship.toml'
output_path = '~/.config/starship.toml'

[templates.vesktop]
input_path = './templates/colors-discord.css'
output_path = '~/.config/vesktop/themes/matugen.theme.css'

[templates.waybar]
input_path = './templates/colors-css.css'
output_path = '~/.config/waybar/css/colors.css'

[templates.zen-chrome]
input_path = './templates/zen-browser/userChrome.css'
output_path = '~/.zen/hj0jj3u6.Default (beta)/chrome/userChrome.css'

[templates.zen-content]
input_path = './templates/zen-browser/userContent.css'
output_path = '~/.zen/hj0jj3u6.Default (beta)/chrome/userContent.css'

