# Shell variables
# Generated by 'wal'
wallpaper="{{image}}"

# Special
background='{{colors.background.default.hex | set_lightness: 15.0 }}'
foreground='{{colors.primary_fixed_dim.default.hex}}'
cursor='{{colors.on_surface.default.hex}}'

# Colors
color0='{{colors.surface.default.hex | set_lightness: 15.0 }}'
color1='{{colors.surface_container_lowest.default.hex | set_lightness: 15.0 }}'
color2='{{colors.surface_container_low.default.hex | set_lightness: 15.0 }}'
color3='{{colors.surface_container.default.hex | set_lightness: 15.0 }}'
color4='{{colors.surface_container_high.default.hex | set_lightness: 15.0 }}'
color5='{{colors.surface_container_highest.default.hex | set_lightness: 15.0 }}'
color6='{{colors.surface_bright.default.hex | set_lightness: 15.0 }}'
color7='{{colors.primary.default.hex | set_lightness: 15.0 }}'
color8='{{colors.error_container.default.hex}}'
color9='{{colors.primary.default.hex}}'
color10='{{colors.error.default.hex}}'
color11='{{colors.secondary.default.hex}}'
color12='{{colors.surface_tint.default.hex}}'
color13='{{colors.tertiary.default.hex}}'
color14='{{colors.outline.default.hex}}'
color15='{{colors.on_tertiary_fixed.default.hex | set_lightness: 15.0 }}'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
