"$schema" = 'https://starship.rs/config-schema.json'

format = """
[ ╭─](fg:color_primary)\
[](fg:color_bg0)\
$os\
$username\
[](bg:color_primary fg:color_bg0)\
$directory\
[](fg:color_primary bg:color_bg0)\
$git_branch\
$git_status\
[](fg:color_bg0 bg:color_bg0)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:color_bg0)\
$line_break$character\
[╰─➤ ](fg:color_primary)
"""

palette = 'matugen'

[palettes.matugen]
color_primary = '{{colors.primary.default.hex}}'
color_bg0 = '{{colors.on_primary_fixed.default.hex}}'
color_bg3 = '#665c54'
color_blue = '#001f27'
color_aqua = '#689d6a'
color_green = '#98971a'
color_yellow = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'


[os]
disabled = false
style = "bg:color_bg0 fg:color_primary"

[os.symbols]
Arch = "󰣇"

[username]
show_always = true
style_user = "bg:color_bg0 fg:color_primary"
style_root = "bg:color_bg0 fg:color_primary"
format = '[ $user ]($style)'

[directory]
style = "fg:color_bg0 bg:color_primary"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = " "
".config" = " "
"hypr" = " "

[git_branch]
symbol = ""
style = "bg:color_background"
format = '[[ $symbol $branch ](fg:color_primary bg:color_bg0)]($style)'

[git_status]
style = "bg:color_bg0"
format = '[[($all_status$ahead_behind )](fg:color_primary bg:color_bg0)]($style)'

[nodejs]
symbol = ""
style = "bg:color_bg0"
format = '[[ $symbol( $version) ](fg:color_primary bg:color_bg0)]($style)'

[c]
symbol = " "
style = "bg:color_bg0"
format = '[[ $symbol( $version) ](fg:color_primary bg:color_bg0)]($style)'

[rust]
symbol = ""
style = "bg:color_bg0"
format = '[[ $symbol( $version) ](fg:color_primary bg:color_bg0)]($style)'

[golang]
symbol = ""
style = "bg:color_bg0"
format = '[[ $symbol( $version) ](fg:color_primary bg:color_bg0)]($style)'

[php]
symbol = ""
style = "bg:color_bg0"
format = '[[ $symbol( $version) ](fg:color_primary bg:color_bg0)]($style)'

[java]
symbol = ""
style = "bg:color_bg0"
format = '[[ $symbol( $version) ](fg:color_primary bg:color_bg0)]($style)'

[kotlin]
symbol = ""
style = "bg:color_bg0"
format = '[[ $symbol( $version) ](fg:color_primary bg:color_bg0)]($style)'

[haskell]
symbol = ""
style = "bg:color_bg0"
format = '[[ $symbol( $version) ](fg:color_primary bg:color_bg0)]($style)'

[python]
symbol = ""
style = "bg:color_bg0"
format = '[[ $symbol( $version) ](fg:color_primary bg:color_bg0)]($style)'

[docker_context]
symbol = ""
style = "bg:color_bg3"
format = '[[ $symbol( $context) ](fg:#83a598 bg:color_bg3)]($style)'

[conda]
style = "bg:color_bg3"
format = '[[ $symbol( $environment) ](fg:#83a598 bg:color_bg3)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:color_background"
format = '[[ $time ](fg:color_bg0 bg:color_primary)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:color_green)'
error_symbol = '[](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_primary)'
